# Generated by Django 5.0.2 on 2026-07-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0007_sesioncliente_grupo'),
        ('pedidos', '0009_pedido_estado_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpago',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_de_grupo', to='mesas.sesioncliente'),
        ),
    ]
