# Generated by Django 5.0.2 on 2026-07-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0006_sesioncliente_ultima_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_grupo', to='mesas.sesioncliente'),
        ),
    ]
