# Generated by Django 5.0.2 on 2026-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0007_sesioncliente_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='es_para_llevar',
            field=models.BooleanField(default=False),
        ),
    ]
